# Generated by Django 4.2 on 2026-03-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook',
            options={'managed': False},
        ),
    ]
